services:
  nginx:
    image: nginx:1.28.0-alpine
    container_name: reverse_proxy
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
     - ./nginx/root:/usr/share/nginx/root
    ports:
     - "3000:3000"

  db-portal:
    image: postgres:17.4-alpine3.21
    container_name: db-portal
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_portal:/var/lib/postgresql/data

  db-aku:
    image: postgres:17.4-alpine3.21
    container_name: db-aku
    ports:
      - "6100:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_aku:/var/lib/postgresql/data

  db-ulf:
    image: postgres:17.4-alpine3.21
    container_name: db-ulf
    ports:
      - "6110:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_ulf:/var/lib/postgresql/data

volumes:
  db_portal:
  db_aku:
  db_ulf: