import Config

# Configure your database
config :ulf, Ulf.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost", # "host.docker.internal", #
  port:     "6110",
  database: "ulf_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ulf, UlfWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4110], # [ip: {0, 0, 0, 0}, port: 4110], #
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "FkFH2S/kstntbdLtNQBypG9PruVsuon/ipRC1vYN6o+JW1xTr7sjIxZd8LOtqGYt",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ulf, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ulf, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# https://hexdocs.pm/phoenix_live_reload/Phoenix.LiveReloader.html
config :phoenix_live_reload, :dirs, [
  "",
  "../gen_ui"  |> Path.expand(),
  "../gen_lib" |> Path.expand(),
]

# Watch static and templates for browser reloading.
config :ulf, UlfWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"gen_ui/.*ex",
      ~r"gen_lib/.*ex",
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ulf_web/(controllers|live|components)/.*(ex|heex)$"
    ],
    prefix: "/ulf",
    root_tag: "root-ulf",
  ],
  reloadable_compilers: [:gettext, :elixir],
  reloadable_apps: [:ulf, :gen_ui, :gen_lib]

# Enable dev routes for dashboard and mailbox
config :ulf, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
